#!/usr/bin/env python3
"""Create the minimal overlay needed to add Mobile Stadium to upstream."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import time
from pathlib import Path


DIRECTORIES = ("tools/bin",)
FILES = (
    "include/mobile_stadium.h",
    "src/mobile_stadium_command.s",
    "src/mobile_stadium_overlay.c",
    "tools/build_mobile_overlays_wsl.sh",
    "tools/localization.py",
    "tools/mobile_save.py",
    "tools/stadium2_mobile_save_converter.py",
    "tools/mobile_stadium.py",
    "tools/sync_localization_kit.py",
    "tools/verify_mobile_interop.py",
    "tools/verify_nrage_mbc30.py",
    "tools/package_mobile_stadium.py",
)

TEXT_FILES = (
    "de.json",
    "de.msg-overrides.json",
    "en.json",
    "en.msg-overrides.json",
    "es.json",
    "es.msg-overrides.json",
    "fr.json",
    "fr.msg-overrides.json",
    "it.json",
    "it.msg-overrides.json",
    "ja.json",
    "us.json",
)

# These are the authored localized replacements. The other ~19,500 graphics
# in the kit are unmodified exports which the build regenerates from the
# supplied regional ROMs.
GRAPHIC_FILES = (
    "archive1_099_000010_ia8_320x37.png",
    "archive1_228_00AC90_rgba16_248x89.png",
    "archive1_229_000010_rgba16_256x137.png",
    "archive1_253_000010_rgba16_160x142.png",
    "archive1_254_000018_rgba16_152x44.png",
    "archive13_055_jpeg_144x96.jpg",
    "archive13_056_jpeg_144x112.jpg",
    "archive13_057_jpeg_144x112.jpg",
    "archive13_058_jpeg_144x112.jpg",
)
GRAPHIC_LANGUAGES = ("us", "en", "au", "fr", "de", "it", "es")


def copy_file(source: Path, destination: Path) -> None:
    if not source.is_file():
        raise FileNotFoundError(source)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--batch", type=Path, required=True)
    args = parser.parse_args()
    repo, output = args.repo.resolve(), args.output.resolve()
    if output.exists():
        # Windows thumbnail/antivirus readers can briefly retain individual
        # PNG/JPG handles while this folder is being replaced.  Retry the
        # exact output directory instead of leaving a half-deleted package.
        for attempt in range(20):
            try:
                shutil.rmtree(output)
                break
            except PermissionError:
                if attempt == 19:
                    raise
                time.sleep(0.1)
    project = output / "pokestadiumgs-master"

    for relative in DIRECTORIES:
        shutil.copytree(
            repo / relative, project / relative,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )
    for relative in FILES:
        copy_file(repo / relative, project / relative)

    # The localization kit remains the editable authority, but ship only its
    # authored changes. Unmodified exported graphics, source mirrors and the
    # 12 MiB generated message hash cache are regenerated by the build.
    kit_source = repo / "stadium2-localization-kit"
    kit_target = project / "stadium2-localization-kit"
    for name in TEXT_FILES:
        copy_file(
            kit_source / "mobile/assets/text" / name,
            kit_target / "mobile/assets/text" / name,
        )
    for code in GRAPHIC_LANGUAGES:
        for name in GRAPHIC_FILES:
            copy_file(
                kit_source / "mobile/assets/graphics" / code / name,
                kit_target / "mobile/assets/graphics" / code / name,
            )
    # This icon is the one additional language-specific replacement.
    copy_file(
        kit_source / "mobile/assets/graphics/it/"
        "archive1_033_000A70_ia8_24x26.png",
        kit_target / "mobile/assets/graphics/it/"
        "archive1_033_000A70_ia8_24x26.png",
    )
    for name in ("de_msg.txt", "en_msg.txt", "es_msg.txt", "fr_msg.txt",
                 "it_msg.txt", "ja-Hrkt_msg.txt"):
        copy_file(kit_source / name, kit_target / name)

    # assets/localization is the generated build workspace, not an authored
    # input. Stage 1 reconstructs its regional archives, executable deltas and
    # manifest from the supplied ROMs; Stage 2 reconstructs its Mobile subtree
    # from stadium2-localization-kit. Do not package either generated mirror.

    copy_file(args.batch.resolve(), project / args.batch.name)
    converter_launcher = repo.parent / "Pokemon Stadium 2 Mobile Save Converter.bat"
    if converter_launcher.is_file():
        copy_file(converter_launcher, project / converter_launcher.name)
    converter_readme = repo.parent / "Pokemon Stadium 2 Mobile Save Converter README.md"
    if converter_readme.is_file():
        copy_file(converter_readme, project / converter_readme.name)
    (project / "README.txt").write_text(
        "Mobile Stadium build overlay\n\n"
        "Merge this pokestadiumgs-master folder over a clean extraction of the\n"
        "base pokestadiumgs-master.zip. Place the required regional Stadium 2\n"
        "ROMs beside that folder, then run Build Mobile Stadium ROMs.bat from\n"
        "inside pokestadiumgs-master.\n\n"
        "Expected source ROM names are Pokemon Stadium 2 (English).n64,\n"
        "Pokemon Stadium 2 (Europe).z64, and the France/Germany/Italy/Spain\n"
        "regional .n64 files used by the localization project.\n\n"
        "The overlay contains only files added or changed by this project. The\n"
        "upstream compiler, unchanged exports, generated mirrors, ROMs, saves,\n"
        "checkpoints, and emulator binaries are deliberately excluded.\n\n"
        "The batch regenerates localization assets, builds all seven ROMs, and\n"
        "overwrites the sibling Mobile Stadium Build Requirements folder with\n"
        "the current minimal overlay after each successful build.\n",
        encoding="utf-8",
    )
    files = {}
    for path in sorted(p for p in project.rglob("*") if p.is_file()):
        if path.name == "manifest.json":
            continue
        files[path.relative_to(project).as_posix()] = {
            "size": path.stat().st_size,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        }
    (project / "manifest.json").write_text(
        json.dumps({"format": 1, "files": files}, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"created {output}: {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
